# Generated by Django 3.1.4 on 2021-06-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerecipes', '0002_auto_20210604_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerecipes.category'),
        ),
    ]
